<?php

namespace Urbant\CConvertBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository
{
    
    public function getContents($searchConditions) {
       $qb = $this->createQueryBuilder('s')
           ->select('s')
           ->addOrderBy('s.created', 'DESC');
        
       if(isset($searchConditions['created_from']) && $searchConditions['created_from'] != '') {
           $qb->andWhere("s.created >= :created_from");
           $qb->setParameter('created_from', $searchConditions['created_from']);
       }
       if(isset($searchConditions['created_to']) && $searchConditions['created_to'] != '') {
           $qb->andWhere("s.created <= :created_to");
           $qb->setParameter('created_to', $searchConditions['created_to']);
       }
       
        return $qb->getQuery()->getResult();
    }
    
    
    /**
     * 
     */
    public function deleteContentForIds($ids) {
        
        if(!is_array($ids) || count($ids) == 0) {
            throw new \UnexpectedValueException('Target ID list was empty.');
        }
        
        $qb = $this->createQueryBuilder('s')
            ->delete('UrbantCConvertBundle:Site', 's');
        
        $idConditions = array();
        $idParams = array();
        foreach($ids as $index=>$id) {
            $key = 's_id' . $index;
            $idConditions[] = ':' . $key;
            $idParams[$key] = $id;
        }
        
        $qb->where('s.id IN ( ' . implode(' , ', $idConditions) . ' )');
        $qb->setParameters($idParams);
        
        return $qb->getQuery()->execute();
    }
    
}