<?php

namespace Urbant\CConvertBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuleRepository extends EntityRepository
{
    
    public function getRules($searchConditions) {
       $qb = $this->createQueryBuilder('r')
           ->select('r')
           ->addOrderBy('r.created', 'DESC');
        
       if(isset($searchConditions['name']) && $searchConditions['name'] != '') {
           $qb->andWhere("r.name LIKE :name_cond");
           $qb->setParameter('name_cond', '%' . $searchConditions['name'] . '%');
       }
       if(isset($searchConditions['created_from']) && $searchConditions['created_from'] != '') {
           $qb->andWhere("r.created >= :created_from");
           $qb->setParameter('created_from', $searchConditions['created_from']);
       }
       if(isset($searchConditions['created_to']) && $searchConditions['created_to'] != '') {
           $qb->andWhere("r.created <= :created_to");
           $qb->setParameter('created_to', $searchConditions['created_to']);
       }
       
        return $qb->getQuery()->getResult();
    }
    
    
    /**
     * 
     */
    public function deleteRuleForIds($ids) {
        
        if(!is_array($ids) || count($ids) == 0) {
            throw new \UnexpectedValueException('Target ID list was empty.');
        }
        
        $qb = $this->createQueryBuilder('r')
            ->delete('UrbantCConvertBundle:Rule', 'r');
        
        $idConditions = array();
        $idParams = array();
        foreach($ids as $index=>$id) {
            $key = 'r_id' . $index;
            $idConditions[] = ':' . $key;
            $idParams[$key] = $id;
        }
        
        $qb->where('r.id IN ( ' . implode(' , ', $idConditions) . ' )');
        $qb->setParameters($idParams);
        
        return $qb->getQuery()->execute();
    }
    
}