<?php

namespace Urbant\CConvertBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
    
    public function getSites() {
        
       $qb = $this->createQueryBuilder('s')
           ->select('s')
           ->addOrderBy('s.created', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
    
    
    /**
     * 
     */
    public function deleteSiteForIds($ids) {
        
        if(!is_array($ids) || count($ids) == 0) {
            throw new \UnexpectedValueException('Target ID list was empty.');
        }
        
        $qb = $this->createQueryBuilder('s')
            ->delete('UrbantCConvertBundle:Site', 's');
        
        $idConditions = array();
        $idParams = array();
        foreach($ids as $index=>$id) {
            $key = 's_id' . $index;
            $idConditions[] = ':' . $key;
            $idParams[$key] = $id;
        }
        
        $qb->where('s.id IN ( ' . implode(' , ', $idConditions) . ' )');
        $qb->setParameters($idParams);
        
        return $qb->getQuery()->execute();
    }
    
}