<?php

namespace Urbant\CConvertBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
    
    public function getSites() {
        
       $qb = $this->createQueryBuilder('s')
           ->select('s')
           ->addOrderBy('s.created', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
    
}