UrbantCConvertBundle_homepage:
    pattern:  /
    defaults: { _controller: UrbantCConvertBundle:Content:list, page: 1 }

UrbantCConvertBundle_rule:
    resource: "@UrbantCConvertBundle/Resources/config/routing/rule.yml"

UrbantCConvertBundle_request:
    resource: "@UrbantCConvertBundle/Resources/config/routing/request.yml"

UrbantCConvertBundle_content:
    resource: "@UrbantCConvertBundle/Resources/config/routing/content.yml"

UrbantCConvertBundle_user:
    resource: "@UrbantCConvertBundle/Resources/config/routing/user.yml"

UrbantCConvertBundle_api:
    resource: "@UrbantCConvertBundle/Resources/config/routing/api.yml"
