parameters:
#    urbant_c_convert.example.class: Urbant\CConvertBundle\Example
    urbant_cconvert.convert_request_service.class: Urbant\CConvertBundle\Service\ConvertRequestService
    urbant_cconvert.content_dir_path: /var/www/data/contents_convert/src/app/contents

services:
#    urbant_c_convert.example:
#        class: %urbant_cconvert.convert.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    urbant_cconvert.convert_request_service:
        class: %urbant_cconvert.convert_request_service.class%
        arguments: [@doctrine.orm.entity_manager]
    twig_extension_text:
        class: Twig_Extensions_Extension_Text
        tags:
            - {name: twig.extension}
