#Bundle default configuration.
parameters:
    urbant_cconvert.convert_request_service.class: Urbant\CConvertBundle\Service\ConvertRequestService
    urbant_cconvert.content_service.class: Urbant\CConvertBundle\Service\ContentService
    urbant_cconvert.content_api_service.class: Urbant\CConvertBundle\Service\ContentApiService
    urbant_cconvert.content_dir_path: /var/www/data/contents_convert/src/app/contents

services:
    urbant_cconvert.convert_request_service:
        class: %urbant_cconvert.convert_request_service.class%
        arguments: [@doctrine.orm.entity_manager]
    urbant_cconvert.content_service:
        class: %urbant_cconvert.content_service.class%
        arguments: [@doctrine.orm.entity_manager]
        calls:
          - [setContainer, [ @service_container ] ]
    urbant_cconvert.content_api_service:
        class: %urbant_cconvert.content_api_service.class%

    twig_extension_text:
        class: Twig_Extensions_Extension_Text
        tags:
            - {name: twig.extension}
    twig_extension_debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - {name: twig.extension}
    
    urbant_twig_extension_text:
        class: Urbant\CConvertBundle\Twig\TextExtension
        tags:
            - {name: twig.extension}

    pagerfanta.view.default:
        class: Pagerfanta\View\DefaultView
        public: false
        tags: [{ name: pagerfanta.view, alias: default }]

    urbant_cconvert.form_element.role_selector:
        class: Urbant\CConvertBundle\Form\Element\RoleSelectorType
        tags:
            - { name: form.type, alias: role_selector }
