# These parameters can be imported into other config files
# by enclosing the key with % (like %database_user%)
# Comments start with '#'
parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     
    database_name:     cc
    database_user:     cc
    database_password: cc

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       
    mailer_password:   

    locale:            en

    secret:            oihjjkdfope90ujnkl

    urbant_cconvert.convert_request_service.class: Urbant\CConvertBundle\Service\ConvertRequestService
    urbant_cconvert.content_service.class: Urbant\CConvertBundle\Service\ContentService
    urbant_cconvert.content_dir_path: /var/www/data/contents_convert/src/app/contents
