---CURRENT: 0 ---

--- VERSION: 1 ---
ALTER TABLE Rule ADD user_id INT DEFAULT NULL;
CREATE INDEX IDX_E6EA03F2A76ED395 ON Rule (user_id);

-- ALTER TABLE DROP INDEX IDX_E6EA03F2A76ED395;
-- ALTER TABLE Rule DROP COLUMN user_id;
